name = "StochasticArithmetic"
uuid = "f771ca10-1b0b-53f6-a01e-a0d756bd6223"
authors = ["François Févotte <fevotte@gmail.com>"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
